<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.mozilla.org/bugzilla.dtd">

<bugzilla version="3.6.4+"
          urlbase="https://bugzilla.mozilla.org/"
          
          maintainer="bugzilla-admin@mozilla.org"
>

    <bug>
          <bug_id>648346</bug_id>
          
          <creation_ts>2011-04-07 13:22:00 -0700</creation_ts>
          <short_desc>mozIAsyncHistory: call error callback instead of throwing</short_desc>
          <delta_ts>2011-04-07 13:22:16 -0700</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>3</classification_id>
          <classification>Components</classification>
          <product>Toolkit</product>
          <component>Places</component>
          <version>unspecified</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>NEW</bug_status>
          
          
          
          
          <status_whiteboard>[places-next-wanted]</status_whiteboard>
          
          <priority>--</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>636393</blocked>
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Philipp von Weitershausen [:philikon]">philipp</reporter>
          <assigned_to name="Nobody; OK to take it and work on it">nobody</assigned_to>
          
          <qa_contact>places</qa_contact>
          <cf_blocking_fennec>---</cf_blocking_fennec>
          <cf_blocking_fx>---</cf_blocking_fx>
          <cf_blocking_20>---</cf_blocking_20>
          <cf_status_20>---</cf_status_20>
          <cf_blocking_192>---</cf_blocking_192>
          <cf_status_192>---</cf_status_192>
          <cf_blocking_191>---</cf_blocking_191>
          <cf_status_191>---</cf_status_191>
          
          
          
          
          
          
          
          
          
          

      

      

      

          <long_desc isprivate="0">
            <commentid>5394983</commentid>
            <who name="Philipp von Weitershausen [:philikon]">philipp</who>
            <bug_when>2011-04-07 13:22:16 -0700</bug_when>
            <thetext>mozIAsyncHistory&apos;s behaviour to throw when just one of the many passed in records are invalid somehow isn&apos;t very useful for implementers. In case of invalid URIs or non-addable URIs, we need to get away from it anyway (bug 636393).</thetext>
          </long_desc>
      
      

    </bug>

</bugzilla>